name: Tests with Pytest

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: apt-get
      run: |
        sudo apt-get install -y libsndfile-dev
        # ffmpeg >= 4.2
        sudo add-apt-repository ppa:jonathonf/ffmpeg-4
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
        LUIGI_CONFIG_PATH=heareval/tasks/luigi.cfg python3 -m heareval.tasks.runner --small all
